### PR TITLE
Add Mega-Linter for Language Agnostic

### PR DESCRIPTION
**Pull request by nvuillam**
**Information:**

- Language: Multi-languages
- Linter: Mega-Linter
- URL: https://nvuillam.github.io/mega-linter/

**Checklist:**

- [x] Only added one linter?
- [x] Is it inside the right language container?
- [x] Is it sorted alphabetically inside the container?
- [x] Does the title follow the template: "Add [LINTER] for [LANGUAGE]."?

For reference, there's some [contributing guidelines](/CONTRIBUTING.md).

### CODE REVIEW

**Comment by nvuillam** [comment]
I don't understand the CI message ... was it automatic or manual ?

If i add the links to all the linters here, it will take half of the page 🙄 

image

**Comment by nvuillam** [comment]
ok, it was a trailing whitespace ;)

**Comment by caramelomartins** [comment]
Thank you for your contribution @nvuillam. I apologize for the delay in merging this!

**Comment by nvuillam** [comment]
No problem, thanks for your validation and have a better year than 2020 :)

**Pull request merged**
