### PR TITLE
Add Oversecured for Java.

### PR DESCRIPTION
**Pull request by sergey-wowwow**
**Information:**

- Language: Java
- Linter: Oversecured
- URL: https://oversecured.com/

**Checklist:**

- [+] Only added one linter?
- [+] Is it inside the right language container?
- [+] Is it sorted alphabetically inside the container?
- [+] Does the title follow the template: "Add [LINTER] for [LANGUAGE]."?

For reference, there's some [contributing guidelines](/CONTRIBUTING.md).

### CODE REVIEW

**Comment by caramelomartins** [comment]
Hello @sergey-wowwow. Thank you for contributing. 

Upon looking into this linter, its maturity and open source contributions seem at its very early stages. There's only 1 commit made 5 months ago and there's not much information about who's using it so I believe we should hold on to adding it to the list. Can we try adding it in a few months if there's any progress?

Again, thank you!

**Comment by sergey-wowwow** [comment]
Hey @caramelomartins,
Which list of contributors? I'm trying to add a commercial service, it doesn't have any lists. Moreover, I'm the founder of it (bagipro from HackerOne, I have some disclosed reports there)

**Comment by caramelomartins** [comment]
In the website, I was able to find source code in https://github.com/oversecured/ovaa, which has no contributors, or any information. Given that the list is aimed at being a "community-driven list" of linters I don't believe adding a commercial product for which you are a founder would be a good idea, it would be more interesting to have someone who has adopted it suggest that it be added to the list.

**Comment by sergey-wowwow** [comment]
@caramelomartins
Ahh the OVAA. Be sure it will be updated on this week. But the main service https://oversecured.com is updated every day.

**Comment by sergey-wowwow** [comment]
@caramelomartins 
Nevertheless, the [OVAA](https://github.com/oversecured/ovaa) was recently updated.

> it would be more interesting to have someone who has adopted it suggest that it be added to the list

Obviously it world be great if someone adds the service to the lists of tools. But how is that possible if nobody knows about it, and learns about its existence from such GitHub repositories as yours? :) I'm sharing a lot of knowledge (check out https://blog.oversecured.com/), so the project is not dead and definitely deserves be added to the list.

**Pull request closed without merging**
