### PR TITLE
Add pug-lint for Pug

### PR DESCRIPTION
**Pull request by Grawl**
**Information:**

- Language: Pug
- Linter: pug-lint
- URL: https://github.com/pugjs/pug-lint

**Checklist:**
- [x] Only added one linter?
- [x] Is it inside the right language container?
- [x] Is it sorted alphabetically inside the container?
- [x] Does the title follow the template:  "Add [LINTER] for [LANGUAGE]."?

### CODE REVIEW

**Comment by caramelomartins** [comment]
@Grawl Brilliant! Thanks for the contribution!

**Comment by Grawl** [comment]
I need more linters! Where can I find more? They can be not much awesome, I just want to know what can I do with existing linters written by community.

**Comment by caramelomartins** [comment]
Hey @Grawl, I don't know much more. https://github.com/mre/awesome-static-analysis seems to have some cool resources. If you find more you are always welcome to make a pull request. :)

**Comment by Grawl** [comment]
Okay thank you!

**Pull request merged**
