### PR TITLE
Add awesome-lint

### PR DESCRIPTION
**Pull request by mlcdf**
:smile:

### CODE REVIEW

**Comment by caramelomartins** [comment]
@mlcdf, what about instead of calling it "Awesome-Lists", calling it "Awesome Lists" without the "-"?

It's seems to make sense, it's a title after all. :smile:

**Comment by mlcdf** [comment]
You mean just `Awesome List` (without the final 's')?

**Comment by caramelomartins** [comment]
Nop, I meant "Awesome Lists" instead of "Awesome-Lists"...feels unnatural to have a "-" in the middle.

**Comment by mlcdf** [comment]
Yeah, I totally agree with you on that. 

My point is just about the final 's'. Currently, there is none (go look at the commit). Would you like me to add one?

**Comment by caramelomartins** [comment]
Ahhh...yes please. Sorry I didn't read that @mlcdf!

**Comment by mlcdf** [comment]
No problem. Here you are! :smile:

**Comment by mlcdf** [comment]
I had forgotten to add the 's' in the link too.

**Comment by caramelomartins** [comment]
Thank you @mlcdf !

**Pull request merged**
