### PR TITLE
Grammar Corrections

### PR DESCRIPTION
**Pull request by shlomif**
Grammar corrections:

* "an" before a vowel
* "JavaScript" capitalisation.

**Information:**

- Language:
- Linter:
- URL:

**Checklist:**

- [ ] Only added one linter?
- [ ] Is it inside the right language container?
- [ ] Is it sorted alphabetically inside the container?
- [ ] Does the title follow the template: "Add [LINTER] for [LANGUAGE]."?

For reference, there's some [contributing guidelines](/CONTRIBUTING.md).

### CODE REVIEW

**Comment by shlomif** [comment]
Hi - ping! Can this be merged soon?

**Comment by caramelomartins** [comment]
Hey,

Your branch has conflicts with the existing `master`, it seems to be based on a previous commit in `master`. Would you be able to freshen up your `master` and then rebase `shlomif-additions-2` on top of `master`?

That way we can merge it smoothly.

Let me know if you need help and I can try pushing directly to your fork.

Thanks!

**Comment by shlomif** [comment]
@caramelomartins : per your request, I pulled master and rebased the new branch now. Please take a look. Thanks!

**Comment by caramelomartins** [comment]
Thank you @shlomif!

**Comment by shlomif** [comment]
Thanks @caramelomartins , and - you're welcome!

**Pull request merged**
